<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pid_control</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="abdo@todo.todo">abdo</maintainer>
  <license>TODO: License declaration</license>
  
  <plugin filename="libgz-sim-diff-drive-system.so"
        name="gz::sim::systems::DiffDrive">
  <left_joint>wheel_left_joint</left_joint>
  <right_joint>wheel_right_joint</right_joint>
  <odom_topic>odom</odom_topic>
  <cmd_vel_topic>cmd_vel</cmd_vel_topic>
</plugin>


  <depend>rclpy</depend>
  <depend>control_interfaces</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
